# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='athletes',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.date(2016, 11, 17)),
            preserve_default=False,
        ),
    ]
